apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: aks-reroot
  namespace: kube-system
  labels:
    k8s-app: aks-reroot
spec:
  selector:
    matchLabels:
      name: aks-reroot
  template:
    metadata:
      labels:
        name: aks-reroot
    spec:
      hostPID: true # For entering the host mont namespace via init
      containers:
      - name: aks-reroot
        image: jpangms/aks-reroot:latest
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
        securityContext:
          privileged: true # For nsenter /proc/1/ns/mnt
        volumeMounts:
        - name: per-boot
          mountPath: /app/per-boot
      terminationGracePeriodSeconds: 30
      volumes:
      - name: per-boot
        hostPath:
          path: /var/lib/cloud/scripts/per-boot
